package fr.ul.miashs.compil.lex;

import java_cup.runtime.Symbol;
import fr.ul.miashs.compil.parser.Symbols; // Use Symbols generated by CUP

%%

%class Lexer
%public
%unicode
%line
%column
%cup

%{
    // Fonction utilitaire pour générer les tokens
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }
%}

/* Expressions régulières de base */
Espace       = [ \t\f\r\n]+
Chiffre      = [0-9]
Entier       = {Chiffre}+
Lettre       = [a-zA-Z_éèêàù]
Identifiant  = {Lettre} ({Lettre} | {Chiffre} | "-")*

/* Commentaires (consigne étape 2) */
CommentaireLigne = "//" .*
CommentaireBloc  = "/*" ~"*/"
Commentaire      = {CommentaireLigne} | {CommentaireBloc}

%%

<YYINITIAL> {

    /* Espaces et Commentaires (ignorés) */
    {Espace}                  { /* ignorer */ }
    {Commentaire}             { /* ignorer */ }

    /* Mots-clés : Portée et Déclarations */
    "aliment"                 { return symbol(Symbols.ALIMENT); }
    "épice"                   { return symbol(Symbols.EPICE); }
    "param"                   { return symbol(Symbols.PARAM); }
    "ingrédients"             { return symbol(Symbols.INGREDIENTS); }
    "repas"                   { return symbol(Symbols.REPAS); }
    "recette"                 { return symbol(Symbols.RECETTE); }

    /* Mots-clés : Types */
    "quantité"                { return symbol(Symbols.QUANTITE); }
    "cuillère"                { return symbol(Symbols.CUILLERE); }
    "petite-cuillère"         { return symbol(Symbols.PETITE_CUILLERE); }
    "vide"                    { return symbol(Symbols.VIDE); }

    /* Mots-clés : Instructions */
    "mélanger"                { return symbol(Symbols.MELANGER); }
    "servir"                  { return symbol(Symbols.SERVIR); }
    "déguster"                { return symbol(Symbols.DEGUSTER); }
    "cuit"                    { return symbol(Symbols.CUIT); }
    "crue"                    { return symbol(Symbols.CRUE); }
    "mijoter"                 { return symbol(Symbols.MIJOTER); }
    "étape"                   { return symbol(Symbols.ETAPE); }
    "prêt"                    { return symbol(Symbols.PRET); }
    "dresser"                 { return symbol(Symbols.DRESSER); }

    /* Opérateurs arithmétiques */
    "ajouter"                 { return symbol(Symbols.AJOUTER); }
    "réduire"                 { return symbol(Symbols.REDUIRE); }
    "monter"                  { return symbol(Symbols.MONTER); }
    "fouetter"                { return symbol(Symbols.FOUETTER); }
    "couper"                  { return symbol(Symbols.COUPER); }

    /* Opérateurs booléens et de comparaison */
    "meilleur"                { return symbol(Symbols.MEILLEUR); }
    "un-peu-meilleur"         { return symbol(Symbols.UN_PEU_MEILLEUR); }
    "pas-bon"                 { return symbol(Symbols.PAS_BON); }
    "un-peu-bon"              { return symbol(Symbols.UN_PEU_BON); }
    "parfait"                 { return symbol(Symbols.PARFAIT); }
    "étonnant"                { return symbol(Symbols.ETONNANT); }
    "mangeable"               { return symbol(Symbols.MANGEABLE); }
    "immangeable"             { return symbol(Symbols.IMMANGEABLE); }

    /* Ponctuations : INVERSÉES (selon votre règle) */
    ")"                       { return symbol(Symbols.PAR_O); }  /* Parenthese ouvrante logique */
    "("                       { return symbol(Symbols.PAR_F); }  /* Parenthese fermante logique */
    "}"                       { return symbol(Symbols.ACCO_O); } /* Accolade ouvrante logique */
    "{"                       { return symbol(Symbols.ACCO_F); } /* Accolade fermante logique */

    /* Autres ponctuations */
    ";"                       { return symbol(Symbols.PTVIRG); }
    ","                       { return symbol(Symbols.VIRG); }
    "."                       { return symbol(Symbols.POINT); }

    /* Valeurs dynamiques : Identifiants et Nombres */
    {Entier}                  { return symbol(Symbols.ENTIER, Integer.parseInt(yytext())); }
    
    /* On place l'identifiant en dernier pour ne pas masquer les mots-clés */
    {Identifiant}             { return symbol(Symbols.IDENT, yytext()); }

    /* Gestion des erreurs (caractère non reconnu) */
    [^]                       { System.err.println("Erreur lexicale à la ligne " + yyline + " : plat non reconnu -> " + yytext()); }
}